repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-shebang-scripts-are-executable

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v14.0.6
  hooks:
  - id: clang-format
    files: src/.*\.cpp|src/.*\.h

- repo: local
  hooks:
  - id: build_and_test
    name: build and test
    entry: ./scripts/build_and_run_tests
    language: script
    pass_filenames: false
